apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wy0ijicgw-go 
  janus-idp.io/tekton: wy0ijicgw-go
  backstage.io/kubernetes-id: wy0ijicgw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wy0ijicgw-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml